export const generateResetPassword = async () => {
    try {
        
    } catch (error) {
        throw new Error(error)
    }
}